apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.apiUiIssuerNode.deployment.name }}
  labels:
    {{- include "polygon-id-issuer.apiUiIssuerNode.deploymentLabels" . | nindent 4 }}
    {{- include "polygon-id-issuer.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.apiUiIssuerNode.deployment.replicaCount }}
  selector:
    matchLabels:
      {{- include "polygon-id-issuer.apiUiIssuerNode.Labels" . | nindent 6 }}
      {{- include "polygon-id-issuer.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "polygon-id-issuer.apiUiIssuerNode.Labels" . | nindent 8 }}
        {{- include "polygon-id-issuer.selectorLabels" . | nindent 8 }}
    spec:
      initContainers:
        - name: {{ .Values.apiUiIssuerNode.deployment.init1.containerName }}
          image: {{ .Values.apiUiIssuerNode.deployment.init1.image.repository }}:{{ .Values.apiUiIssuerNode.deployment.init1.image.tag }}
          imagePullPolicy: {{ .Values.apiUiIssuerNode.deployment.init1.imagePullPolicy | quote }}
          env:
            - name: {{ include "helpers.issuer-db-url" .}}
              value: {{ quote .Values.apiUiIssuerNode.deployment.init1.env.issuerDatabaseUrl }}
            - name: {{ include "helpers.issuer-key-store-addr" .}}
              value: {{ quote .Values.apiUiIssuerNode.deployment.init1.env.issuerKeyStoreAddress }}
          envFrom:
            - configMapRef:
                name: {{ .Values.apiUiIssuerNode.deployment.init1.apiconfigMapRef }}
          command: {{ .Values.apiUiIssuerNode.deployment.init1.command }}
          volumeMounts: {{- toYaml .Values.apiUiIssuerNode.deployment.init1.volumeMounts | nindent 12 }}     
        
        - name: {{ .Values.apiUiIssuerNode.deployment.init2.containerName }}
          image: {{ .Values.apiUiIssuerNode.deployment.init2.image.repository }}:{{ .Values.apiUiIssuerNode.deployment.init2.image.tag }}
          imagePullPolicy: {{ .Values.apiUiIssuerNode.deployment.init2.imagePullPolicy | quote }}
          env:
            - name: {{ include "helpers.issuer-db-url" .}}
              value: {{ quote .Values.apiUiIssuerNode.deployment.init1.env.issuerDatabaseUrl }}
            - name: {{ include "helpers.issuer-key-store-addr" .}}
              value: {{ quote .Values.apiUiIssuerNode.deployment.init1.env.issuerKeyStoreAddress }}
          envFrom:
            - configMapRef:
                name: {{ .Values.apiUiIssuerNode.deployment.init2.apiconfigMapRef }}
            - configMapRef:
                name: {{ .Values.apiUiIssuerNode.deployment.init2.apiuiconfigMapRef }}
          command: {{ .Values.apiUiIssuerNode.deployment.init2.command }}
          args: {{ .Values.apiUiIssuerNode.deployment.init2.args }}
          volumeMounts: {{- toYaml .Values.apiUiIssuerNode.deployment.init2.volumeMounts | nindent 10 }}     
      containers:
        - name: {{ .Values.apiUiIssuerNode.deployment.apiUi.containerName }}
          image: {{ .Values.apiUiIssuerNode.deployment.apiUi.image.repository }}:{{ .Values.apiUiIssuerNode.deployment.apiUi.image.tag }}
          imagePullPolicy: {{ .Values.apiUiIssuerNode.deployment.apiUi.imagePullPolicy | quote }}
          ports:
            - containerPort: {{ .Values.apiUiIssuerNode.deployment.apiUi.containerPort }}
          env:
            - name: {{ include "helpers.issuer-db-url" .}}
              value: {{ quote .Values.apiUiIssuerNode.deployment.apiUi.env.issuerDatabaseUrl }}
            - name: {{ include "helpers.issuer-key-store-addr" .}}
              value: {{ quote .Values.apiUiIssuerNode.deployment.apiUi.env.issuerKeyStoreAddress }}
          envFrom:
            - configMapRef:
                name: {{ .Values.apiUiIssuerNode.deployment.apiUi.apiconfigMapRef }}
            - configMapRef:
                name: {{ .Values.apiUiIssuerNode.deployment.init.apiuiconfigMapRef }}
          args: {{ .Values.apiUiIssuerNode.deployment.apiUi.args }}
          command: {{ .Values.apiUiIssuerNode.deployment.apiUi.command }}
          livenessProbe:
            httpGet:
              path: {{ .Values.apiUiIssuerNode.deployment.apiUi.livenessProbe.path }}
              port: {{ .Values.apiUiIssuerNode.deployment.apiUi.livenessProbe.port }}
              httpHeaders:
              - name: {{ .Values.apiUiIssuerNode.deployment.apiUi.livenessProbe.name }}
                value: {{ .Values.apiUiIssuerNode.deployment.apiUi.livenessProbe.value }}
            initialDelaySeconds: {{ .Values.apiUiIssuerNode.deployment.apiUi.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.apiUiIssuerNode.deployment.apiUi.livenessProbe.periodSeconds }}
          volumeMounts: {{- toYaml .Values.apiUiIssuerNode.deployment.apiUi.volumeMounts | nindent 12 }} 
      volumes:
      - name: {{ .Values.apiIssuerNode.pvc.volumeName }}
        persistentVolumeClaim:
            claimName: {{ .Values.apiIssuerNode.pvc.name }}
      - name: {{  .Values.vaultIssuerNode.pvc.volumeName }} 
        persistentVolumeClaim:
            claimName: {{ .Values.vaultIssuerNode.pvc.vault }} 