apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.apiUiIssuerNode.service.name }}
  labels: 
    {{- include "polygon-id-issuer.staticLabel" . | nindent 4 }}
    {{- include "polygon-id-issuer.labels" . | nindent 4 }}
spec:
  type: {{ .Values.apiUiIssuerNode.service.type }}
  selector:
    {{- include "polygon-id-issuer.apiUiIssuerNode.Labels" . | nindent 4 }}
    {{- include "polygon-id-issuer.selectorLabels" . | nindent 4 }}
  {{- with .Values.apiUiIssuerNode.service.ports }}
  ports: 
    {{-  toYaml . | nindent 4 }}
  {{- end }}
