apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.uiIssuerNode.service.name }}
  labels:
    {{- include "polygon-id-issuer.staticLabel" . | nindent 4 }}
    {{- include "polygon-id-issuer.labels" . | nindent 4 }}
spec:
  type: {{ .Values.uiIssuerNode.service.type }}
  selector:
    {{- include "polygon-id-issuer.uiIssuerNode.Labels" . | nindent 4 }}
    {{- include "polygon-id-issuer.selectorLabels" . | nindent 4 }}
  {{- with .Values.uiIssuerNode.service.ports }}
  ports: 
    {{-  toYaml . | nindent 4 }}
  {{- end }}