apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.vaultIssuerNode.pvc.vault }} 
  labels:
  {{- include "polygon-id-issuer.labels" . | nindent 4 }}
spec:
  storageClassName: {{ .Values.vaultIssuerNode.pvc.storageClass  }}
  accessModes:
  - {{ .Values.vaultIssuerNode.pvc.accessModes }}
  resources:
    requests:
      storage: {{ .Values.vaultIssuerNode.pvc.storageRequest  }}
  