# Default values for polygon-id-issuer
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
apiIssuerNode:
  deployment:
    replicaCount: 1
    name: api-issuer-node
    env:
      issuerDatabaseUrl: postgres://$(ISSUER_DB_USER):$(ISSUER_DB_PASSWORD)@postgres-issuer-node-svc:$(ISSUER_DB_PORT)/$(ISSUER_DB_NAME)?sslmode=disable
      issuerKeyStoreAddress: http://vault-issuer-node-svc:$(ISSUER_KEY_STORE_PORT)
    image:
      repository: gcr.io/polygon-public/polygon-id/issuernode
      # Overrides the image tag whose default is the chart appVersion.
      tag: '1.0'
    imagePullPolicy: Always
    labels:
      app: api-issuer-node-deployment
    livenessProbe:
      name: Custom-Header
      value: Awesome
      path: /status
      port: 3001
      initialDelaySeconds: 3
      periodSeconds: 60 
    apiconfigMapRef: issuer-node-api-configmap
    args: 
      - '"./migrate; ./platform"'
    command:  
      - '"sh", "-c"' 
    volume: vault-volume
    claimName: vault-issuer-node-pvc
    containerPort: 3001
    containerName: api
    mountPath: /vault/data
  service:
    name: api-issuer-node-svc
    ports:
    - port: 3001
      protocol: TCP
      targetPort: 3001
    type: NodePort
    selector: api-issuer-node
    labels:
      app: issuer-node
  configMap:
    issuerApiAuthPassword: password
    issuerApiAuthUser: user
    issuerCircuitPath: ./pkg/credentials/circuits
    issuerDbName: platformid
    issuerDbPassword: strongpasswordapp
    issuerDbPort: "5432"
    issuerDbUser: polygonid
    issuerEthereumConfirmationBlockCount: "10"
    issuerEthereumConfirmationTimeOut: 10s
    issuerEthereumContractAddress: 0x134B1BE34911E39A8397ec6289782989729807a4
    issuerEthereumDefaultGasLimit: "600000"
    issuerEthereumMaxGasPrice: "1000000"
    issuerEthereumMinGasPrice: "0"
    issuerEthereumReceiptTimeout: 600s
    issuerEthereumResolverPrefix: polygon:mumbai
    issuerEthereumRpcResponseTimeout: 5s
    issuerEthereumUrl: https://polygon-mumbai.g.alchemy.com/v2/xaP2_t9EUM2VYDgCgMI0k9KqDyJPvZ89
    issuerEthereumWaitBlockCycleTime: 30s
    issuerEthereumWaitReceiptCycleTime: 30s
    issuerKeyStorePluginIden3MountPath: iden3
    issuerKeyStorePort: "8200"
    issuerLogLevel: "-4"
    issuerLogMode: "2"
    issuerNativeProofGenerationEnabled: "true"
    issuerOnchainCheckStatusFrequency: 1m
    issuerOnchainPublishStateFrequency: 1m
    issuerProverServerUrl: http://localhost:8002
    issuerProverTimeout: 600s
    issuerPublishKeyPath: pbkey
    issuerRedisUrl: redis://@redis-issuer-node-svc:6379/1
    issuerReverseHashServiceEnabled: "false"
    issuerServerPort: "3001"
    issuerServerUrl: http://localhost:3001
    issuerName: issuer-node-api-configmap
  pvc:
    storageClass: standard-rwo
    storageRequest: 250Mi
    accessModes: ReadWriteOnce
    volumeName: issuer-node-volume
    name: issuer-node-pvc

apiUiIssuerNode:
  deployment:
    replicaCount: 1
    name: api-ui-issuer-node
    apiUi:
      containerName: api-ui
      env:
        issuerDatabaseUrl: postgres://$(ISSUER_DB_USER):$(ISSUER_DB_PASSWORD)@postgres-issuer-node-svc:$(ISSUER_DB_PORT)/$(ISSUER_DB_NAME)?sslmode=disable
        issuerKeyStoreAddress: http://vault-issuer-node-svc:$(ISSUER_KEY_STORE_PORT)
      image:
        repository: gcr.io/polygon-public/polygon-id/issuernode
        # Overrides the image tag whose default is the chart appVersion.
        tag: '1.0'
      imagePullPolicy: Always 
      args: 
        - '"./migrate; ./platform_ui"'
      command:  
        - '"sh", "-c"'
      livenessProbe:
        name: Custom-Header
        value: Awesome
        path: /status
        port: 3002
        initialDelaySeconds: 3
        periodSeconds: 60
      containerPort: 3002
      apiconfigMapRef: issuer-node-api-configmap
      volumeMounts:
      - name: issuer-node-volume
        mountPath: /did/data
      - name: vault-volume
        mountPath: /vault/data
    init:
      containerName: i
      env:
        issuerDatabaseUrl: postgres://$(ISSUER_DB_USER):$(ISSUER_DB_PASSWORD)@postgres-issuer-node-svc:$(ISSUER_DB_PORT)/$(ISSUER_DB_NAME)?sslmode=disable
        issuerKeyStoreAddress: http://vault-issuer-node-svc:$(ISSUER_KEY_STORE_PORT)
      image:
        repository: gcr.io/polygon-public/polygon-id/issuernode
        # Overrides the image tag whose default is the chart appVersion.
        tag: '1.0'
      imagePullPolicy: Always
      args: 
        - '"sleep 30; ./migrate; ./issuer_initializer;"'
      command:  
        - '"sh", "-c"'
      apiuiconfigMapRef: issuer-node-api-ui-configmap
      volumeMounts:
      - name: issuer-node-volume
        mountPath: /did/data/
        readOnly: false
      - name: vault-volume
        mountPath: /vault/data
    labels:
      app: api-ui-issuer-node-deployment
    volume: issuer-node
  service:
    name: api-ui-issuer-node-svc
    ports:
    - port: 3002
      protocol: TCP
      targetPort: 3002
    type: NodePort
    selector: api-ui-issuer-node
  configMap:
    issuerApiEnvironment: local
    issuerApiIdentityBlockchain: polygon
    issuerApiIdentityMethod: polygonid
    issuerApiIdentityNetwork: mumbai
    issuerApiUiAuthPassword: password-api
    issuerApiUiAuthUser: user-api
    issuerApiUiIssuerName: my issuer
    issuerApiUiSchemaCache: "false"
    issuerApiUiServerPort: "3002"
    issuerApiUiServerUrl: https://5eaa-190-191-21-57.ngrok-free.app/issuer-admin
    issuerApiName: issuer-node-api-ui-configmap
  

notificationsIssuerNode:
  deployment:
    replicaCount: 1
    name: notifications-issuer-node
    env:
      issuerDatabaseUrl: postgres://$(ISSUER_DB_USER):$(ISSUER_DB_PASSWORD)@postgres-issuer-node-svc:$(ISSUER_DB_PORT)/$(ISSUER_DB_NAME)?sslmode=disable
      issuerKeyStoreAddress: http://vault-issuer-node-svc:$(ISSUER_KEY_STORE_PORT)
    image:
      repository:  gcr.io/polygon-public/polygon-id/issuernode
      # Overrides the image tag whose default is the chart appVersion.
      tag: '1.0'
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - name: issuer-node-volume
      mountPath: /did/data
    - name: vault-volume
      mountPath: /vault/data    
    labels: 
      app: notifications-issuer-node-deployment
    containerName: notifications
    args: 
      - '"./notifications"'
    command:  
      - '"sh", "-c"'

pendingPublisherIssuerNode:
  deployment:
    replicaCount: 1
    name: pending-publisher-issuer-node
    env:
      issuerDatabaseUrl: postgres://$(ISSUER_DB_USER):$(ISSUER_DB_PASSWORD)@postgres-issuer-node-svc:$(ISSUER_DB_PORT)/$(ISSUER_DB_NAME)?sslmode=disable
      issuerKeyStoreAddress: http://vault-issuer-node-svc:$(ISSUER_KEY_STORE_PORT)
    image:
      repository: gcr.io/polygon-public/polygon-id/issuernode
      # Overrides the image tag whose default is the chart appVersion.
      tag: '1.0'
    imagePullPolicy: Always
    volumeMounts:
    - name: issuer-node-volume
      mountPath: /did/data
    - name: vault-volume
      mountPath: /vault/data
    labels: 
      app: pending-publisher-issuer-node-deployment
    containerName: pending-publisher
    args: 
      - '"./pending_publisher"'
    command:  
      - '"sh", "-c"'


uiIssuerNode:
  deployment:
    replicaCount: 1
    name: ui-issuer-node
    image:
      repository: gcr.io/polygon-public/polygon-id/issuernode-ui
      # Overrides the image tag whose default is the chart appVersion.
      tag: '1.0'
    imagePullPolicy: Always
    uiconfigMapRef: issuer-node-api-ui-configmap
    containerName: ui
    containerPort: 80
    labels: 
      app: ui-issuer-node-deployment
  service:
    name: ui-issuer-node-svc
    ports:
    - port: 8080
      protocol: TCP
      targetPort: 80
    type: NodePort
    selector: ui-issuer-node
  configMap:
    issuerApiUiAuthPassword: password-api
    issuerApiUiAuthUser: user-api
    issuerApiUiIssuerName: my issuer k8s
    issuerUiAuthPassword: password-ui
    issuerUiAuthUsername: user-ui
    issuerUiBlockExplorerUrl: https://mumbai.polygonscan.com
    issuerUiIpfsGatewayUrl: https://ipfs.io
    issuerApiUiName: issuer-node-ui-configmap

postgresIssuerNode:
  deployment:
    replicaCount: 1
    name: postgres-issuer-node
    image:
      repository: gcr.io/polygon-public/polygon-id/postgres14
      # Overrides the image tag whose default is the chart appVersion.
      tag: '1.0'
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - name: postgresdata
      mountPath: /var/lib/postgresql/polygon
    - name: postgres-initdb
      mountPath: /docker-entrypoint-initdb.d
      #readOnly: true
    labels: 
      app: postgres-issuer-node-deployment
    postgresconfigMapRef: postgres-secret
    containerPort: 5432
    containerName: postgres
    volumeName: postgres-initdb
    items: init.sql
  service:
    name: postgres-issuer-node-svc
    ports:
    - port: 5432
      protocol: TCP
      targetPort: 5432
    selector: postgres-issuer-node
  configMap:
    initSql: |-
      ALTER USER polygonid SUPERUSER;
    postgresDb: platformid
    postgresPassword: strongpasswordapp
    postgresUser: polygonid
    postgresName: postgres-secret  
  pvc:
    storageClass: standard-rwo
    storageRequest: 5Gi
    accessModes: ReadWriteOnce
    volumeName: postgresdata
    postgres: postgresql-issuer-node-pvc

redisIssuerNode:
  deployment:
    replicaCount: 1
    name: redis-issuer-node
    image:
      repository: gcr.io/polygon-public/polygon-id/redis
      # Overrides the image tag whose default is the chart appVersion.
      tag: '1.0'
    resources:
      limits:
        cpu: "1"
        memory: 2Gi
      requests:
        cpu: "0.5"
        memory: 1Gi  
    labels: 
      app: redis-issuer-node
    containerPort: 6379
    containerName: redis
  service:
    name: redis-issuer-node-svc
    ports:
    - port: 6379
      protocol: TCP
      targetPort: 6379
    selector: redis-issuer-node
    
vaultIssuerNode:
  deployment:
    replicaCount: 1
    name: vault-issuer-node
    labels: 
      app: vault-issuer-node-deployment
    containerPort: 8200
    containerName: vault
    command:  
      - '"sh", "-c", "/vault/config/init.sh"' 
    volumeMounts:
    - name: vault-volume
      mountPath: /vault/plugins
    - name: vault-volume
      mountPath: /vault/data
    - name: vault-volume
      mountPath: /vault/file
    - name: vault-config
      mountPath: /vault/config
    vault:
      containerSecurityContext:
        capabilities:
          add: IPC_LOCK
      env:
        name1: VAULT_ADDR
        vaultAddr: http://127.0.0.1:8200
        name2: PRIVATE_KEY
        secretKeyRef: 
          name: private-key-secret
          key: private-key
      image:
        repository: gcr.io/polygon-public/polygon-id/vault
        # Overrides the image tag whose default is the chart appVersion.
        tag: '1.0'
      imagePullPolicy: IfNotPresent
  pvc:
    storageClass: standard-rwo
    storageRequest: 250Mi
    accessModes: ReadWriteOnce
    volumeName: vault-volume
    vault: vault-issuer-node-pvc
  service:
    name: vault-issuer-node-svc
    ports:
    - port: 8200
      protocol: TCP
      targetPort: 8200
    selector: vault-issuer-node
  configMap:
    vaultConfigName: vault-config
    vaultConfigPath1: vault.json
    vaultConfigPath2: init.sh
    initSh: |-

      #!/bin/sh
      echo "VAULT CONFIGURATION SCRIPT"
      echo "===================================";

      vault server -config=/vault/config/vault.json 1>&1 2>&1 &

      # export VAULT_SKIP_VERIFY='true'

      export VAULT_ADDR=http://127.0.0.1:8200
      # Parse unsealed keys
      sleep 5

      FILE=/vault/data/init.out
      if [ ! -e "$FILE" ]; then
          echo -e "===== Initialize the Vault ====="
          vault operator init > /vault/data/init.out
      fi

      UNSEAL_KEY_1=$(grep "Unseal Key 1" /vault/data/init.out | cut -c 15-)
      UNSEAL_KEY_2=$(grep "Unseal Key 2" /vault/data/init.out | cut -c 15-)
      UNSEAL_KEY_3=$(grep "Unseal Key 3" /vault/data/init.out | cut -c 15-)
      UNSEAL_KEY_4=$(grep "Unseal Key 4" /vault/data/init.out | cut -c 15-)
      UNSEAL_KEY_5=$(grep "Unseal Key 5" /vault/data/init.out | cut -c 15-)

      TOKEN=$(grep "Token" /vault/data/init.out | cut -c 21-)

      echo -e "\n===== Unseal the Vault ====="

      vault operator unseal $UNSEAL_KEY_1
      vault operator unseal $UNSEAL_KEY_2
      vault operator unseal $UNSEAL_KEY_3

      vault login $TOKEN
      vault secrets enable -path=secret/ kv-v2
      echo -e "\n===== ENABLED KV secrets ====="

      IDEN3_PLUGIN_PATH="/vault/plugins/vault-plugin-secrets-iden3"

      if [ ! -e "$IDEN3_PLUGIN_PATH" ]; then
        echo "===== IDEN3 Plugin not found: downloading... ====="
          IDEN3_PLUGIN_ARCH=amd64
          IDEN3_PLUGIN_VERSION=0.0.6
          if [ `uname -m` == "aarch64" ]; then
              IDEN3_PLUGIN_ARCH=arm64
          fi
          VAULT_IDEN3_PLUGIN_URL="https://github.com/iden3/vault-plugin-secrets-iden3/releases/download/v${IDEN3_PLUGIN_VERSION}/vault-plugin-secrets-iden3_${IDEN3_PLUGIN_VERSION}_linux_${IDEN3_PLUGIN_ARCH}.tar.gz"
          wget -q -O - ${VAULT_IDEN3_PLUGIN_URL} | tar -C /vault/plugins -xzf - vault-plugin-secrets-iden3
      fi

      apk add -q openssl
      IDEN3_PLUGIN_SHA256=`openssl dgst -r -sha256 ${IDEN3_PLUGIN_PATH} | awk '{print $1}'`
      vault plugin register -sha256=$IDEN3_PLUGIN_SHA256 vault-plugin-secrets-iden3
      vault secrets enable -path=iden3 vault-plugin-secrets-iden3

      chmod 755 /vault/file -R

      echo "===== ENABLED IDEN3 ====="
      export vault_token="token:${TOKEN}"
      echo $vault_token
      
      rm /vault/data/token.txt
      echo $TOKEN > /vault/data/token.txt
      tail -f /dev/null  
    vaultJson: |-
      {                                    
      "listener":  {                     
        "tcp":  {                        
          "address":  "0.0.0.0:8200",  
          "tls_disable":  "true"         
        }                                
      },                                 
      "backend": {                       
        "file": {                        
          "path": "/vault/file"          
        }                                
      },                                 
      "default_lease_ttl": "168h",       
      "max_lease_ttl": "0h",
      "api_addr": "http://0.0.0.0:8200",
      "plugin_directory" : "/vault/plugins",
      "disable_mlock": true
      }
      
secrets:
  name: private-key-secret
  type: Opaque
  privateKey: NDU2NTE4ZTFlZWRlYzBkY2JiODUwMTMzMzEyZDRmNzEwOGIxYjBiOWMzZWI5YmYwNTA5MmIxMzY3NDY3NDkyOQ==

ingress:
  enabled: true
  name: issuer-node-ingress
  annotations: 
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.allow-http: "true"
    # networking.gke.io/managed-certificates: managed-cert
    # kubernetes.io/ingress.global-static-ip-name: polygon-ip


  apphost:
    paths:
      - path: /v1/
        serviceName: api-ui-issuer-node-svc
        servicePort: 3002
      - path: /
        serviceName: api-ui-issuer-node-svc
        servicePort: 3002
  uihost: 
    paths:
      - path: /
        serviceName: ui-issuer-node-svc
        servicePort: 8080

managedcertificate:
  name: polygon-cert

uidomain: ui.example.com
appdomain: app.example.com
staticip: nil
