apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.vaultIssuerNode.configMap.vaultConfigName }}
  labels:
    {{ include "polygon-id-issuer.staticLabel" . }}
    {{- include "polygon-id-issuer.labels" . | nindent 4 }}
data:
  vault.json: {{- .Values.vaultIssuerNode.configMap.vaultJson | toYaml | indent 4 }}    
  init.sh: |
    {{-  .Values.vaultIssuerNode.configMap.initSh | replace "\n" "\n      " }}